name: With server
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: kyleawayan/cypress-with-firebase-emulator-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: CYPRESS_NEXT_PUBLIC_APIKEY=${{ secrets.NEXT_PUBLIC_APIKEY }},CYPRESS_NEXT_PUBLIC_AUTHDOMAIN=${{ secrets.NEXT_PUBLIC_AUTHDOMAIN }},CYPRESS_NEXT_PUBLIC_PROJECTID=${{ secrets.NEXT_PUBLIC_PROJECTID }},CYPRESS_NEXT_PUBLIC_APPID=${{ secrets.NEXT_PUBLIC_APPID }},CYPRESS_NEXT_PUBLIC_STORAGEBUCKET=${{ secrets.NEXT_PUBLIC_STORAGEBUCKET }}
          build: yarn buildDev
          start: yarn ciCypress
          config: video=false,screenshotOnRunFailure=false
