name: With server
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: kyleawayan/cypress-with-firebase-emulator-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn buildDev
          start: yarn ciCypress
          config: video=false,screenshotOnRunFailure=false
